sudo: required

services: 
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t superknife0512/docker-learner .

script:
  - docker run --env CI=true superknife0512/docker-learner npm test -- --coverage

